<?php
include('header.php');
?>
<div class="section">
   <div class="abt ppol">
   <h2>Privacy Policy</h2>

		<p>M.R Associates respects your privacy and recognizes the need to protect the personally identifiable information (any information by which you can be identified, such as name, address, and telephone number) you share with us. We would like to assure you that we follow appropriate standards when it comes to protecting your privacy on our web sites.</p>
		<p>In general, you can visit M.R Associates website without telling us who you are or revealing any personal information about yourself. We track the Internet address of the domains from which people visit us and analyze this data for trends and statistics, but the individual user remains anonymous.</p>

		<p>There are times when we may collect personal information from you such as name, physical address or telephone number. It is our intent to inform you before we do that and to tell you what we intend to do with the information. Generally, you will have the option not to provide the information, and in the future you will be able to "opt out" of certain uses of the information. If you choose not to provide the information we request, you can still visit the M.R Associates website, but you may be unable to access certain options, offers and services.</p>


		<p>M.R Associates will not sell, trade or disclose to third parties any information derived from the registration for, or use of, any online service (including names and addresses) without the consent of the user or customer (except as required by subpoena, search warrant, or other legal process or in the case of imminent physical harm to the user or others). M.R Associates will allow suppliers to access the information for purposes of confirming your registration and providing you with benefits you are entitled to.</p>


		<p>M.R Associates will take appropriate steps to protect the information you share with us. We have implemented technology and security features and strict policy guidelines to safeguard the privacy of your personally identifiable information from unauthorized access and improper use or disclosure. M.R Associates will continue to enhance our security procedures as new technology becomes available.</p>


		<p>This website uses Google Analytics 'cookies' to collect standard internet log information and visitor behaviour information in an anonymous form. The information generated by the cookie about your use of the website (including your IP address) is transmitted to Google. This information is then used to evaluate visitors use of the website and to compile statistical reports on website activity for TribeNautix.com.</p>

		<p>M.R Associates will never (and will not allow any third party) use the statistical analytics tool to track or to collect any personally identifiable information of visitors to our site. Google will not associate your IP address with any other data held by Google. Neither we nor Google will link, or seek to link, an IP address with the identity of a computer user. We will not associate any data gathered from this site with any personally identifying information from any source, unless you explicity submit that information via a fill-in form on our website.</p>

		<p>M.R Associates uses Remarketing tools with Google Analytics to advertise online. Third-party vendors, including Google, may show M.R Associates ads on sites you visit, across the Internet. M.R Associates and third-party vendors, including Google, use first-party cookies (such as the Google Analytics cookie) and third-party cookies (such as the DoubleClick cookie) together to inform, optimize, and serve ads based on past visits to M.R Associates.com from similar users.</p>

		<p>M.R Associates and third party vendors, use first-party cookies (such as the Google Analytics cookies) and third-party cookies (such as the DoubleClick cookie) together to report how your ad impressions, other uses of ad services, and interactions with these ad impressions and ad services are related to visits to M.R Associates.com.</p>

		<p>Using the Ads Settings (https://www.google.com/settings/ads), to opt-out of Google Analytics for Display Advertising and customize Google Display Network ads.</p>

		<p>You can also use the following Google Analytic's opt-outs - https://tools.google.com/dlpage/gaoptout/</p>

		<p>If our privacy policy changes in the future, it will be posted here and a new effective date will be shown. You should access our privacy policy regularly to ensure you understand our current policies. When you register with M.R Associates.com, we or any of our partners/affiliate/group companies may contact you from time to time to provide the offers/information of such products/services that we believe may benefit you.</p>

		<p>Thank you for using M.R Associates!</p>
   </div>
</div>

<script type="text/javascript">
$(document).ready(function()
{
$(".from").change(function()
{

var from=$(this).val();
var dataString = 'id='+ from;


$.ajax
({
type: "POST",
url: "to.php",
data: dataString,
cache: false,
success: function(html)
{
$(".to").html(html);
}
});

});

});



</script>


<?php
include('footer.php')
?>